FROM python:3.7-slim

RUN apt-get update

COPY requirements.txt .
RUN pip install --upgrade pip wheel setuptools
RUN pip install -r requirements.txt

ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p $DAGSTER_HOME
COPY cool-beans/cool_beans/dagster.yaml $DAGSTER_HOME
COPY cool-beans/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
